### PR TITLE
docs: Add links and pip best practices

### PR DESCRIPTION
**Pull request by matthewfeickert**
Add links to the README for [`fax`](https://github.com/gehring/fax) and the [`demo_training`](https://github.com/pyhf/neos/blob/master/demo_training.ipynb) notebook. Additionally use `python -m pip` for best practice.

### CODE REVIEW

**Review by phinate — COMMENTED** [review]
Thanks for the edits to the README -- I'll make the appropriate changes to have them agree with @gehring's PR.

**Comment by matthewfeickert** [comment]
> Thanks for the edits to the README -- I'll make the appropriate changes

I think that it is best to keep things PR focused, so it would be better to rebase the PR and resolve the issues there then to just add them in on `master`. @phinate If you don't have conerns here, I can do the rebasing to fix this up &mdash; I will need to edit `master` though.

**Comment by phinate** [comment]
> > Thanks for the edits to the README -- I'll make the appropriate changes
> 
> I think that it is best to keep things PR focused, so it would be better to rebase the PR and resolve the issues there then to just add them in on `master`. @phinate If you don't have conerns here, I can do the rebasing to fix this up — I will need to edit `master` though.

That sounds like a much better idea, thanks :)

**Comment by matthewfeickert** [comment]
@phinate This should be good to go now. You're going to want to do the following though locally first as we reworte history a bit on `master` (which is probably obvious to you):
```
$ git checkout master
$ git reset --hard origin/master
```

Also, I apologize if my suggestions came across as pushy or trying to tell you what to do. This is your project and original awesome work. So feel free to let me know (or have @lukasheinrich gently remind me :slightly_smiling_face:) if I ever come across as too opinionated or pushy.

**Pull request merged**
