### PR TITLE
docs: Add Binder support

### PR DESCRIPTION
**Pull request by matthewfeickert**
Add [Binder](https://mybinder.org/) support by using the [`postBuild`](https://mybinder.readthedocs.io/en/latest/config_files.html#postbuild-run-code-after-installing-the-environment) configuration file to install `neos` from the local repo. Additionally add a Binder launch badge to the `README` that will open up to the `demo_training.ipynb`.

[Binder](https://mybinder.org/v2/gh/pyhf/neos/master?filepath=demo_training.ipynb)

### CODE REVIEW

**Review by lukasheinrich — APPROVED** [review]

**Comment by lukasheinrich** [comment]
Thanks @matthewfeickert . LGTM. @phinate ?

**Comment by lukasheinrich** [comment]
some tests are failing.. a nbdev issue?

**Comment by matthewfeickert** [comment]
> some tests are failing.. a nbdev issue?

Yes, they have been [failing since your commit yesterday](https://github.com/pyhf/neos/commit/9cc6f25a5fc661fc1e0b36a8fb456826423c6ff3) @lukasheinrich

**Comment by phinate** [comment]
Yeah, the tests are nbdev-related. It requires you to install some git hooks that remove notebook metadata. I think Lukas just didn't run `nbdev_install_git_hooks` before editing index.ipynb :)

I'll nbdev-ify the README changes (it's autogenerated from index.ipynb), but LGTM too!

**Pull request merged**
